version: "3.9"

services:
  web:
    build:
      context: .
      target: web

    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"

    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      target: worker

    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"

  redis:
    image: docker.io/library/redis:6.2
