name: CI

on:
  push:

jobs:
  build-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/sandhose/tp-siris-service-discovery

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker meta (web)
        id: meta-web
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.IMAGE }}/web"
          bake-target: docker-metadata-action-web
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta (worker)
        id: meta-worker
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.IMAGE }}/worker"
          bake-target: docker-metadata-action-worker
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          files: |
            docker-bake.hcl
            ${{ steps.meta-web.outputs.bake-file }}
            ${{ steps.meta-worker.outputs.bake-file }}
          set: |
            base.output=type=image,push=true
            base.cache-from=type=registry,ref=${{ env.IMAGE }}:buildcache
            base.cache-to=type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
